### ISSUE TITLE
No servers added to memcache connection ERROR

### ISSUE THREAD

**Issue by thagxt** [akirk/php-ratelimiter#1]
I'm having problems when trying to run the script

 `Warning: Memcache::get(): No servers added to memcache connection in /public_html/path/to/script.php on line 45`

problem comes from this:
 `$this->memcache->set($key, 1, 0, $minutes * 60 + 1);`

any thoughts on how to fix that?

**Comment by akirk** [comment]
You need to add servers to your Memcache object, like so:

```
$memcache = new Memcache;
$memcache->addServer('127.0.0.1', 11211);
$rateLimiter = new RateLimiter($memcache, $_SERVER["REMOTE_ADDR"]);
```

**Comment by thagxt** [comment]
that worked! thanks :+1:
